sudo: false
dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install: pip install tox-travis codecov
script: tox
deploy:
  provider: pypi
  user: KyleJamesWalker
  on:
    tags: true
    python: '3.7'
  password:
    secure: NrKdXGqT3wDg28jSwVT1tPhcfUt1cosBqovyDBBLR8TXV7NGyB3xc+/ESnXyBj8T/Z95MH49ZlGgGaSpAvfplj7nSzLYMsp56aKn74jLoPuIilendwvh7Pz4V+JVGOzvB8Im87GaYZOwyTNbdOk6f8+Ac8GdGLWNVG/0F96kWqHpEnv/0ebWm3os1xSR+cRDSifPJ8BpUVhJAe8q315dGYrTRF1booxjZ4Cv5BGrlsLvczaO4PGcmisuOCcMuRPSSBM7BaGMEG+5X8vRTSIIKaSlO86+DMlbvGIjhCARIEdnw26a/j43+GftYmO0I2WmBIKs8RU2d341ge3uHVutuhdED9ZsGbet+fuOrizPDjgWBgEAbtoopGYi5tpIvKebowpdh0KIVOkkTgK2IiKApHD5B33eO9ok4k7JD+w0AWQ6skRPby+akkWh/hX8rUdHBNrpazVbyp65Qvm6T278eIUPEK964U6O1d71XtREB9CjT83s7cr6fo4bMC+Cgl+ghn6P5brAHXGogKkHPi4ZH9+en1RVCZDQ/TaFW1Qa7bCzMP2JGIu2cQC6Mkv7YEYJyaNZnBTIYlmwYGx4jVBvkahPRmYeJU9/8lhdkIPgZdzvE2Eq7VeNp/5YwkTl3+Xr1NDC+7jkhtw9Fq8C1NVzXY48qWEj6GcENCBbJiS5tB8=
after_success:
- codecov
